//! The frozen reference outputs, and the claims the manifest makes about them.
//!
//! These are the files every later differential compares against, so before any
//! of that means anything they have to be the files the manifest describes,
//! produced by the ACadSharp and SDK the manifest names, in the schema this
//! suite understands.
//!
//! All offline, all under an ordinary `cargo test`: no .NET, no ACadSharp, no
//! network. Regenerating them needs all three, which is exactly why it is a
//! separate command with an explicit `--accept` and not something a test run
//! can do by accident.
//!
//! Each check is paired with the state that makes it fail. A reference suite
//! whose guards cannot go red would let an empty `fixtures/expected/` read as a
//! healthy baseline, which is worse than having no baseline at all.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use acadsharp_rs_tests::fixtures;
use serde_json::Value;

/// The canonical schema version this suite can read.
///
/// Written out rather than taken from the manifest. Deriving it would make the
/// check vacuous: a reference regenerated by a schema 2 exporter would rewrite
/// the manifest to say 2 and the assertion would follow it.
const SCHEMA: u64 = 1;

/// Same reasoning for the SVG dialect.
const SVG_SCHEMA: u64 = 1;

/// Record names that are geometry a viewer draws.
const PRIMITIVE_RECORDS: &[&str] = &[
    "line", "polyline", "arc", "circle", "ellipse", "spline", "polygon", "text", "point",
];

/// The deterministic warning categories the schema allows.
const WARNING_CATEGORIES: &[&str] = &[
    "unsupported_entity",
    "invalid_entity",
    "missing_reference",
    "missing_font",
    "malformed_geometry",
    "reader_notification",
    "unknown",
];

fn repo_root() -> &'static Path {
    Path::new(env!("CARGO_MANIFEST_DIR"))
}

fn reference_project() -> PathBuf {
    repo_root().join("reference").join("ACadSharp.Reference")
}

/// Every record of one fixture's frozen canonical output.
///
/// Goes through `fixtures::load_reference_jsonl`, which decompresses and checks
/// the sha256 before returning anything, so a test that gets a record list has
/// already proved the bytes are the manifest's.
fn records(fixture: &fixtures::DwgFixture) -> Vec<Value> {
    let bytes = fixture
        .load_reference_jsonl()
        .unwrap_or_else(|e| panic!("{e}"));
    let text = String::from_utf8(bytes)
        .unwrap_or_else(|e| panic!("{}: reference output is not UTF-8: {e}", fixture.id));

    assert!(
        text.ends_with('\n'),
        "{}: the canonical stream has no final newline",
        fixture.id
    );
    assert!(
        !text.contains('\r'),
        "{}: the canonical stream carries a carriage return; the format is LF only",
        fixture.id
    );

    text.lines()
        .enumerate()
        .map(|(index, line)| {
            serde_json::from_str(line)
                .unwrap_or_else(|e| panic!("{}: line {} is not JSON: {e}", fixture.id, index + 1))
        })
        .collect()
}

fn record_name(value: &Value) -> &str {
    value.get("record").and_then(Value::as_str).unwrap_or("")
}

#[test]
fn every_fixture_carries_a_frozen_reference() {
    // The positive control for the whole file. Without it, a corpus that lost
    // its reference rows would make every per-fixture test below iterate over
    // nothing and pass.
    assert!(
        !fixtures::all().is_empty(),
        "the corpus is empty, so nothing below is checking anything"
    );

    let mut without = Vec::new();
    for fixture in fixtures::all() {
        if fixture.reference_jsonl.is_none() || fixture.reference_svg.is_none() {
            without.push(fixture.id.as_str());
        }
    }

    assert!(
        without.is_empty(),
        "these fixtures have no frozen reference output: {without:?}. A fixture the \
         differential cannot compare is a version the suite claims to cover and does not. \
         Run `python3 tools/regenerate_reference.py regenerate --accept`."
    );
}

#[test]
fn the_frozen_output_is_the_one_the_manifest_describes() {
    let mut checked = 0usize;
    for fixture in fixtures::all() {
        // Both loaders verify the hash themselves and name the fixture on a
        // mismatch, so an unwrap here is the assertion.
        let jsonl = fixture
            .load_reference_jsonl()
            .unwrap_or_else(|e| panic!("{e}"));
        let svg = fixture
            .load_reference_svg()
            .unwrap_or_else(|e| panic!("{e}"));
        assert!(
            !jsonl.is_empty(),
            "{}: the reference JSONL decompressed to nothing",
            fixture.id
        );
        assert!(
            !svg.is_empty(),
            "{}: the reference SVG is empty",
            fixture.id
        );
        checked += 1;
    }

    assert_eq!(
        checked,
        fixtures::all().len(),
        "only {checked} of {} fixtures were checked",
        fixtures::all().len()
    );
}

#[test]
fn the_canonical_stream_says_what_it_should() {
    for fixture in fixtures::all() {
        let rows = records(fixture);
        assert!(
            !rows.is_empty(),
            "{}: the reference output has no records at all",
            fixture.id
        );

        assert_eq!(
            record_name(&rows[0]),
            "document",
            "{}: the stream must open with the document record, section 14 fixes the order",
            fixture.id
        );
        assert_eq!(
            rows[0].get("acad_version").and_then(Value::as_str),
            Some(fixture.acad_version.as_str()),
            "{}: the document record and the manifest disagree about the DWG version, so one \
             of them is describing a different file",
            fixture.id
        );
        assert_eq!(
            rows[0].get("format").and_then(Value::as_str),
            Some("dwg"),
            "{}: the document record's format is not dwg",
            fixture.id
        );

        for (index, row) in rows.iter().enumerate() {
            assert_eq!(
                row.get("schema").and_then(Value::as_u64),
                Some(SCHEMA),
                "{}: record {} does not carry schema {SCHEMA}",
                fixture.id,
                index + 1
            );
        }

        let views = rows.iter().filter(|r| record_name(r) == "view").count();
        assert!(
            views > 0,
            "{}: no view record, so no entity record has anywhere to belong",
            fixture.id
        );

        let primitives = rows
            .iter()
            .filter(|r| PRIMITIVE_RECORDS.contains(&record_name(r)))
            .count();
        assert!(
            primitives > 0,
            "{}: the reference holds no primitive records. A differential over an empty \
             stream compares two absences and passes, so an empty reference is refused \
             rather than frozen.",
            fixture.id
        );
    }
}

#[test]
fn the_stream_is_ordered_the_way_the_schema_says() {
    // document, then every view, then every entity, then every warning. The
    // regeneration tool hashes this file, so the order is part of the contract
    // rather than an artefact of how the extractor happened to walk.
    for fixture in fixtures::all() {
        let rows = records(fixture);
        let mut stage = 0usize;
        for (index, row) in rows.iter().enumerate() {
            let name = record_name(row);
            let expected = match name {
                "document" => 0,
                "view" => 1,
                "warning" => 3,
                _ => 2,
            };
            assert!(
                expected >= stage,
                "{}: record {} is a {name} after a later-stage record; the canonical order is \
                 document, view, entities, warnings",
                fixture.id,
                index + 1
            );
            stage = expected;
        }
    }
}

#[test]
fn view_records_are_numbered_from_zero_and_entities_point_at_one() {
    for fixture in fixtures::all() {
        let rows = records(fixture);
        let mut indices = Vec::new();
        for row in rows.iter().filter(|r| record_name(r) == "view") {
            let index = row
                .get("index")
                .and_then(Value::as_u64)
                .unwrap_or_else(|| panic!("{}: a view record has no index", fixture.id));
            let kind = row.get("kind").and_then(Value::as_str).unwrap_or("");
            assert!(
                matches!(kind, "model" | "layout" | "unknown"),
                "{}: view kind {kind:?} is not one of model, layout, unknown",
                fixture.id
            );
            indices.push(index);
        }

        let want: Vec<u64> = (0..indices.len() as u64).collect();
        assert_eq!(
            indices, want,
            "{}: view indices are not a gapless run from zero",
            fixture.id
        );

        let valid: BTreeSet<u64> = indices.into_iter().collect();
        for row in &rows {
            if let Some(view) = row.get("view").and_then(Value::as_u64) {
                assert!(
                    valid.contains(&view),
                    "{}: a {} record points at view {view}, which no view record declares",
                    fixture.id,
                    record_name(row)
                );
            }
        }
    }
}

#[test]
fn curve_records_stay_curves() {
    // Section 5: a circle is a centre and a radius, not four hundred vertices.
    // If a future change started flattening them this is what notices, because
    // a flattened corpus still parses, still hashes and still looks healthy.
    let mut totals: BTreeMap<&str, usize> = BTreeMap::new();
    for fixture in fixtures::all() {
        let rows = records(fixture);
        for row in &rows {
            match record_name(row) {
                "circle" => {
                    *totals.entry("circle").or_default() += 1;
                    for key in ["cx", "cy", "cz", "radius", "nx", "ny", "nz"] {
                        assert!(
                            row.get(key).and_then(Value::as_f64).is_some(),
                            "{}: a circle record has no {key}",
                            fixture.id
                        );
                    }
                }
                "arc" => {
                    *totals.entry("arc").or_default() += 1;
                    let start = row.get("start").and_then(Value::as_f64).unwrap();
                    let end = row.get("end").and_then(Value::as_f64).unwrap();
                    assert!(
                        end > start,
                        "{}: an arc record sweeps from {start} to {end}; the canonical form \
                         always sweeps counter-clockwise, so end is strictly greater",
                        fixture.id
                    );
                }
                "ellipse" => {
                    *totals.entry("ellipse").or_default() += 1;
                    let ratio = row.get("ratio").and_then(Value::as_f64).unwrap();
                    assert!(
                        ratio > 0.0 && ratio <= 1.0,
                        "{}: ellipse ratio {ratio} is not in (0, 1]",
                        fixture.id
                    );
                }
                "spline" => {
                    *totals.entry("spline").or_default() += 1;
                    let control = row.get("control_points").and_then(Value::as_array).unwrap();
                    let fit = row.get("fit_points").and_then(Value::as_array).unwrap();
                    assert!(
                        !control.is_empty() || !fit.is_empty(),
                        "{}: a spline record carries neither control nor fit points, so \
                         nothing can reconstruct it",
                        fixture.id
                    );
                }
                "polyline" => {
                    let points = row.get("points").and_then(Value::as_array).unwrap();
                    let bulges = row.get("bulges").and_then(Value::as_array).unwrap();
                    assert_eq!(
                        points.len(),
                        bulges.len(),
                        "{}: a polyline record has {} points and {} bulges; the schema says \
                         one bulge per vertex, always present",
                        fixture.id,
                        points.len(),
                        bulges.len()
                    );
                }
                _ => {}
            }
        }
    }

    // The positive control. Without it, an extractor that stopped emitting
    // curves entirely would satisfy every assertion above by never running one.
    for kind in ["circle", "arc", "ellipse", "spline"] {
        assert!(
            totals.get(kind).copied().unwrap_or(0) > 0,
            "the corpus produced no {kind} records at all, so the check that they stay \
             analytic ran over nothing. Counted: {totals:?}"
        );
    }
}

#[test]
fn warning_records_are_deterministic_and_sorted() {
    for fixture in fixtures::all() {
        let rows = records(fixture);
        let warnings: Vec<&Value> = rows
            .iter()
            .filter(|r| record_name(r) == "warning")
            .collect();
        assert!(
            !warnings.is_empty(),
            "{}: no warning records. Every sample in this corpus carries entity types the \
             oracle cannot represent, so zero warnings means they are being dropped silently \
             rather than reported.",
            fixture.id
        );

        let mut previous: Option<(String, String, String)> = None;
        for warning in &warnings {
            let category = warning
                .get("category")
                .and_then(Value::as_str)
                .unwrap_or("");
            let entity_type = warning
                .get("entity_type")
                .and_then(Value::as_str)
                .unwrap_or("");
            let detail = warning.get("detail").and_then(Value::as_str).unwrap_or("");

            assert!(
                WARNING_CATEGORIES.contains(&category),
                "{}: warning category {category:?} is not one the schema defines",
                fixture.id
            );

            // A DWG handle in a warning is the classic way a "deterministic"
            // artefact stops being comparable: handles are stable inside one
            // file and meaningless across two, so the same drawing saved twice
            // would differ only in numbers nothing can compare.
            assert!(
                !detail.chars().any(|c| c.is_ascii_digit())
                    || detail.starts_with("recursion_limit_")
                    || detail.starts_with("array_too_large_"),
                "{}: warning detail {detail:?} carries a number. Only the two limit details \
                 may, and they carry a constant rather than a handle.",
                fixture.id
            );

            let key = (
                category.to_string(),
                entity_type.to_string(),
                detail.to_string(),
            );
            if let Some(before) = &previous {
                assert!(
                    *before <= key,
                    "{}: warnings are out of order, {before:?} came before {key:?}. They are \
                     sorted by a stable key precisely so the reader's walk order cannot reach \
                     the hash.",
                    fixture.id
                );
            }
            previous = Some(key);
        }
    }
}

#[test]
fn the_svg_is_the_reference_viewer_styling() {
    for fixture in fixtures::all() {
        let bytes = fixture
            .load_reference_svg()
            .unwrap_or_else(|e| panic!("{e}"));
        let text = String::from_utf8(bytes)
            .unwrap_or_else(|e| panic!("{}: reference SVG is not UTF-8: {e}", fixture.id));

        assert!(
            text.starts_with("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"),
            "{}: the SVG does not open with the XML declaration",
            fixture.id
        );
        assert!(
            text.ends_with("</svg>\n"),
            "{}: the SVG has no final newline after the root element",
            fixture.id
        );
        assert!(
            !text.contains('\r'),
            "{}: the SVG carries a carriage return",
            fixture.id
        );
        assert_eq!(
            text.matches("<svg ").count(),
            1,
            "{}: the SVG does not have exactly one root element",
            fixture.id
        );
        assert!(
            text.contains("viewBox=\""),
            "{}: the SVG has no viewBox, so the drawing bounds are not stored in it",
            fixture.id
        );
        assert!(
            text.contains("fill=\"#FFFFFF\""),
            "{}: the SVG has no white background rectangle",
            fixture.id
        );
        assert!(
            text.contains("stroke=\"#000000\""),
            "{}: the SVG does not draw in black",
            fixture.id
        );
        assert!(
            text.contains("vector-effect=\"non-scaling-stroke\""),
            "{}: the SVG does not ask for hairlines, so stroke width would scale with zoom",
            fixture.id
        );
        assert!(
            text.contains("font-family=\"sans-serif\""),
            "{}: the SVG does not use the generic font family, so it would depend on a local \
             AutoCAD or SHX font being installed",
            fixture.id
        );
        assert!(
            !text.contains(".shx") && !text.to_ascii_lowercase().contains(".ttf"),
            "{}: the SVG names a font file, which makes the visual reference depend on the \
             machine that renders it",
            fixture.id
        );
    }
}

#[test]
fn every_row_agrees_with_the_toolchain_that_produced_it() {
    let locked = locked_acadsharp_version();
    let sdk = pinned_sdk_version();
    let upstream = &fixtures::upstream().commit;

    for fixture in fixtures::all() {
        assert_eq!(
            fixture.acadsharp_reference_version.as_deref(),
            Some(locked.as_str()),
            "{}: the manifest says the reference came from ACadSharp {:?} but \
             reference/ACadSharp.Reference/packages.lock.json locks {locked}. A restore today \
             would install a different package than the one that produced this file.",
            fixture.id,
            fixture.acadsharp_reference_version
        );
        assert_eq!(
            fixture.acadsharp_reference_commit.as_deref(),
            Some(upstream.as_str()),
            "{}: acadsharp_reference_commit does not match upstream.commit",
            fixture.id
        );
        assert_eq!(
            fixture.dotnet_sdk.as_deref(),
            Some(sdk.as_str()),
            "{}: the manifest says SDK {:?} but reference/global.json pins {sdk}",
            fixture.id,
            fixture.dotnet_sdk
        );
        assert_eq!(
            fixture.reference_schema,
            Some(SCHEMA as u32),
            "{}: reference_schema is not {SCHEMA}, which is the only schema this suite reads",
            fixture.id
        );
        assert_eq!(
            fixture.svg_schema,
            Some(SVG_SCHEMA as u32),
            "{}: svg_schema is not {SVG_SCHEMA}",
            fixture.id
        );
    }
}

/// The ACadSharp version the lock file actually pins.
///
/// Read from the lock rather than the csproj because the lock is what
/// `--locked-mode` enforces, so it is the one that cannot be wrong about what
/// a restore installs.
fn locked_acadsharp_version() -> String {
    let path = reference_project().join("packages.lock.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{} must be readable: {e}", path.display()));
    let lock: Value = serde_json::from_str(&text).expect("packages.lock.json must be JSON");

    let mut found = Vec::new();
    for framework in lock["dependencies"]
        .as_object()
        .expect("dependencies")
        .values()
    {
        if let Some(resolved) = framework["ACadSharp"]["resolved"].as_str() {
            found.push(resolved.to_string());
        }
    }
    assert_eq!(
        found.len(),
        1,
        "expected exactly one locked ACadSharp, found {found:?}"
    );
    found.remove(0)
}

fn pinned_sdk_version() -> String {
    let path = repo_root().join("reference").join("global.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{} must be readable: {e}", path.display()));
    let global: Value = serde_json::from_str(&text).expect("global.json must be JSON");
    global["sdk"]["version"]
        .as_str()
        .expect("global.json must pin sdk.version")
        .to_string()
}

#[test]
fn the_oracle_depends_on_acadsharp_and_nothing_else() {
    // The independence requirement, as a property of the dependency graph
    // rather than an intention. An oracle that shared the production NativeAOT
    // shim, the ABI encoder or the Rust exporter could carry the same
    // normalization bug as the system under test and still compare equal.
    let csproj = reference_project().join("ACadSharp.Reference.csproj");
    let text = std::fs::read_to_string(&csproj)
        .unwrap_or_else(|e| panic!("{} must be readable: {e}", csproj.display()));

    let packages = text.matches("<PackageReference").count();
    assert_eq!(
        packages, 1,
        "the oracle's csproj has {packages} PackageReference entries; it may have exactly \
         one, ACadSharp. Adding a second is how the independent oracle stops being one."
    );
    assert!(
        text.contains("Include=\"ACadSharp\""),
        "the oracle's single PackageReference is not ACadSharp"
    );
    assert!(
        !text.contains("<ProjectReference"),
        "the oracle's csproj carries a ProjectReference"
    );
    assert!(
        text.contains("<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>"),
        "the oracle does not restore with a lock file, so its ACadSharp version is whatever \
         the next restore resolves"
    );
}

#[test]
fn nothing_under_reference_reaches_for_the_production_stack() {
    // The independence requirement as a text property rather than an intention.
    // An oracle that shared the production NativeAOT shim, the C ABI encoder or
    // the Rust exporter could carry the same normalization bug as the system
    // under test and the differential would still pass.
    //
    // Every needle here is a name that can only appear in code that genuinely
    // reaches for the production stack. The repository's prose says "acadsharp-rs"
    // constantly, including in this comment, so that name is deliberately not a
    // needle: a guard that fires on its own explanation gets relaxed on its first
    // run, and a relaxed guard is worse than none. The csproj having exactly one
    // PackageReference and no ProjectReference is the check that actually binds,
    // and it lives in the test above.
    const FORBIDDEN: &[(&str, &str)] = &[
        ("Viprs.", "the production shim's namespace"),
        ("viprs_acad_", "the C ABI the shim exports"),
        ("PublishAot>true", "a NativeAOT publish"),
        ("PMTiles", "the tile format"),
        ("MapLibre", "the renderer"),
    ];

    // Scoped to the oracle project, not to all of `reference/`. The oracle is
    // the thing that has to be independent; its test project legitimately names
    // every one of these, because asserting the same property from inside the
    // .NET build is part of what it is for.
    let root = reference_project();
    let mut offences = Vec::new();
    let mut scanned = 0usize;
    for path in files_under(&root, &|p| {
        matches!(
            p.extension().and_then(|e| e.to_str()),
            Some("cs" | "csproj" | "sln" | "json" | "config")
        )
    }) {
        scanned += 1;
        let text = std::fs::read_to_string(&path).expect("source file readable");
        let relative = path.strip_prefix(repo_root()).unwrap_or(&path);
        let code = match path.extension().and_then(|e| e.to_str()) {
            Some("cs") => strip_line_comments(&text),
            Some("csproj" | "config" | "sln") => strip_xml_comments(&text),
            _ => text.clone(),
        };
        for (needle, what) in FORBIDDEN {
            if code.contains(needle) {
                offences.push(format!("{}: {what} ({needle})", relative.display()));
            }
        }
    }

    // Positive control: a walker that returned nothing would make this pass
    // over an empty set, which is how a guard quietly stops guarding.
    assert!(
        scanned >= 10,
        "only scanned {scanned} files under {}, which is fewer than the project has",
        root.display()
    );
    assert!(
        offences.is_empty(),
        "the reference oracle reaches into the production stack: {offences:?}. It must not: \
         two implementations that share code can share a bug and still agree."
    );
}

/// A C# file with its `//` and `///` comments removed.
///
/// Crude, and knowingly so: it cuts a `//` inside a string literal too. That
/// costs nothing for a name check and it keeps the explanations in this
/// repository from tripping the guard that explains them.
fn strip_line_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for line in text.lines() {
        out.push_str(line.split("//").next().unwrap_or(""));
        out.push('\n');
    }
    out
}

/// An XML file with its `<!-- -->` comments removed.
fn strip_xml_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    loop {
        match rest.find("<!--") {
            Some(at) => {
                out.push_str(&rest[..at]);
                match rest[at..].find("-->") {
                    Some(close) => rest = &rest[at + close + 3..],
                    None => return out,
                }
            }
            None => {
                out.push_str(rest);
                return out;
            }
        }
    }
}

#[test]
fn no_workflow_can_accept_a_regeneration() {
    // Both accept gates: `--accept` on the regeneration tool, and the
    // environment variable the .NET self-test's expectation writer needs. CI
    // must never be able to use either, or an ACadSharp bump would rewrite the
    // expectations it was supposed to be caught by and go green.
    const GATES: &[&str] = &["--accept", "ACADSHARP_REFERENCE_ACCEPT_SELFTEST"];
    let workflows = repo_root().join(".github").join("workflows");
    let mut offences = Vec::new();
    let mut scanned = 0usize;
    for path in files_under(&workflows, &|p| {
        matches!(p.extension().and_then(|e| e.to_str()), Some("yml" | "yaml"))
    }) {
        scanned += 1;
        let text = std::fs::read_to_string(&path).expect("workflow readable");
        let relative = path.strip_prefix(repo_root()).unwrap_or(&path);
        for line in text.lines() {
            // The comment that explains the rule is allowed to quote the gate.
            let code = line.split('#').next().unwrap_or("");
            for gate in GATES {
                if code.contains(gate) {
                    offences.push(format!("{}: {}", relative.display(), line.trim()));
                }
            }
        }
    }

    assert!(
        scanned > 0,
        "no workflow files were scanned, so this guard checked nothing"
    );
    assert!(
        offences.is_empty(),
        "these workflow lines open an accept gate: {offences:?}. Regeneration is a human \
         decision with a diff attached, never something a job does on its own."
    );
}

fn files_under(dir: &Path, keep: &dyn Fn(&Path) -> bool) -> Vec<PathBuf> {
    let mut found = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(current) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&current) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            let name = entry.file_name();
            let name = name.to_string_lossy();
            if path.is_dir() {
                // Build output is generated, per-architecture and not committed.
                if name == "bin" || name == "obj" {
                    continue;
                }
                stack.push(path);
            } else if keep(&path) {
                found.push(path);
            }
        }
    }
    found.sort();
    found
}
